//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wipief
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public string code { get; set; }
        public string service { get; set; }
        public string price { get; set; }
        public string resultType { get; set; }
        public string analizers { get; set; }
    }
}
